Repository Wolox/react-bootstrap, pull requests merged in 2020-02, with the labels that each got.

#106 Fix optional chaining
  generators/app/constants.js
Labels: bug, configuration

#101 Added easier way to fix problem. Added automatic node version.
  README.md
Labels: configuration, enhancement

#98 Update README.md
  README.md
Labels: configuration

#102 Add jenkins
  .woloxci/Dockerfile
  .woloxci/config.yml
  Jenkinsfile
Labels: configuration, enhancement

#109 The three conventions of hoc added in Spinner component
  generators/app/constants.js
  generators/app/templates/src/app/components/Spinner/components/constants.js
  generators/app/templates/src/app/components/Spinner/components/constants.ts
  generators/app/templates/src/app/components/Spinner/components/loading.js
  generators/app/templates/src/app/components/Spinner/components/loading.tsx
  generators/app/templates/src/app/components/Spinner/index.js
  generators/app/templates/src/app/components/Spinner/index.tsx
  generators/app/templates/src/utils/displayName.ts
Labels: components, development

#104 Refactor checkbox component
  generators/app/templates/docs/Checkbox.md
  generators/app/templates/src/app/components/Checkbox/index.js
  generators/app/templates/src/app/components/Checkbox/index.tsx
  generators/app/templates/src/app/components/Checkbox/layout.js
  generators/app/templates/src/scss/components.scss
  generators/app/templates/src/scss/variables/_colors.scss
Labels: components
